#server:
 # port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: Li123456
    username: root
  redis:
    # Redis 单机单实例
    database: 0
    host: 101.200.80.154
    port: 6379
    password: Li123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl